### ISSUE TITLE
特地来感谢您,解决了我的机器问题.希望能再加一个修改DVMT值的选项..

### ISSUE THREAD

**Issue by 277383761** [dfc643/dk110-igpu-fixer#1]
因为我听别说人黑苹果+4K 60hz显示器要修改DVMT值为128或更高....
而这个bios里找不到这个DVMT开关项....
直接DP输出4k屏幕会有闪烁的现象..

**Comment by dfc643** [comment]
有相关文章吗，有的话我抽空看看 @277383761

**Comment by 277383761** [comment]
> 有相关文章吗，有的话我抽空看看@277383761

暂时没有相关的文章了,4k60hz闪烁的问题我使用了一个hdmi转vga的空接头解决了.非常奇葩的解决了DP输出4k屏的方案.哈哈哈.

**Comment by dfc643** [comment]
@277383761 好的，感谢你的反馈，我这边先关闭问题了，后续有其他问题再发起就可以了 😄

**Comment by dfc643** [comment]
已添加
